-- Dữ liệu 214 bộ thủ tiếng Trung phồn thể
INSERT INTO public.handicrafts (name, pinyin, stroke, vietnamMeaning, englishMeaning, indonesiaMeaning) VALUES
('一', 'yī', 1, 'Nhất: Một, thứ nhất, khởi đầu các số đo, thuộc về dương, bao quát hết thảy.', 'One, first', 'Satu, pertama'),
('丨', 'gǔn', 1, 'Cổn: Nét sổ, đường thẳng đứng trên thông xuống dưới.', 'Vertical line', 'Garis vertikal'),
('丶', 'zhǔ', 1, 'Chủ: Nét chấm, một điểm.', 'Dot', 'Titik'),
('丿', 'piě', 1, 'Phiệt: Nét phẩy, nét nghiêng từ phải qua trái, chỉ động tác.', 'Slash, sweep', 'Garis miring ke kiri'),
('乙', 'yǐ', 1, 'Ất: Can thứ hai trong mười can (Giáp, Ất, Bính, Đinh...).', 'Second of the ten Heavenly Stems', 'Kedua dari sepuluh Batang Langit'),
('亅', 'jué', 1, 'Quyết: Nét sổ có móc, cái móc.', 'Hook', 'Kait'),
('二', 'èr', 2, 'Nhị: Hai, số hai.', 'Two', 'Dua'),
('亠', 'tóu', 2, 'Đầu: Phần đầu, nắp đậy.', 'Lid, top', 'Tutup, atas'),
('人', 'rén', 2, 'Nhân: Người.', 'Man, person', 'Orang, manusia'),
('儿', 'ér', 2, 'Nhi: Trẻ con, người, chân.', 'Son, child', 'Anak laki-laki, anak'),
('入', 'rù', 2, 'Nhập: Vào, đi vào.', 'Enter', 'Masuk'),
('八', 'bā', 2, 'Bát: Tám, số tám.', 'Eight', 'Delapan'),
('冂', 'jiōng', 2, 'Quynh: Vùng biên giới xa, vùng hoang vu.', 'Wide, border', 'Perbatasan, luas'),
('冖', 'mì', 2, 'Mịch: Trùm khăn lên, che đậy.', 'Cover', 'Penutup'),
('冫', 'bīng', 2, 'Băng: Nước đá, băng giá.', 'Ice', 'Es'),
('几', 'jī', 2, 'Kỷ: Cái ghế nhỏ, bàn nhỏ.', 'Small table', 'Meja kecil'),
('凵', 'qǔ', 2, 'Khảm: Há miệng chờ hứng, đồ đựng.', 'Receptacle', 'Wadah'),
('刀', 'dāo', 2, 'Đao: Con dao, vũ khí.', 'Knife', 'Pisau'),
('力', 'lì', 2, 'Lực: Sức mạnh, sức lực.', 'Power, force', 'Kekuatan, tenaga'),
('勹', 'bāo', 2, 'Bao: Bao bọc, gói ghém.', 'Wrap', 'Bungkus'),
('匕', 'bǐ', 2, 'Chủy: Cái thìa, muỗng.', 'Spoon', 'Sendok'),
('匚', 'fāng', 2, 'Phương: Tủ đựng, rương, hòm.', 'Box', 'Kotak'),
('匸', 'xǐ', 2, 'Hệ: Che đậy, giấu giếm.', 'Hiding enclosure', 'Penutup tersembunyi'),
('十', 'shí', 2, 'Thập: Mười, số mười.', 'Ten', 'Sepuluh'),
('卜', 'bǔ', 2, 'Bốc: Xem bói, bói toán.', 'Divination', 'Ramalan'),
('卩', 'jié', 2, 'Tiết: Đốt tre, đốt xương, dấu ấn.', 'Seal', 'Segel'),
('厂', 'hǎn', 2, 'Hán: Sườn núi, vách đá.', 'Cliff', 'Tebing'),
('厶', 'sī', 2, 'Khư: Tư, riêng tư, cá nhân.', 'Private', 'Pribadi'),
('又', 'yòu', 2, 'Hựu: Lại, thêm nữa, lặp lại.', 'Right hand, again', 'Tangan kanan, lagi'),
('口', 'kǒu', 3, 'Khẩu: Cái miệng.', 'Mouth', 'Mulut'),
('囗', 'wéi', 3, 'Vi: Chu vi, bao quanh.', 'Enclosure', 'Kurungan'),
('土', 'tǔ', 3, 'Thổ: Đất.', 'Earth', 'Tanah'),
('士', 'shì', 3, 'Sĩ: Người có học, quan, lính.', 'Scholar', 'Sarjana'),
('夂', 'zhǐ', 3, 'Trĩ: Bước đi chậm.', 'Go', 'Pergi'),
('夊', 'suī', 3, 'Truy: Đi chậm chạp, kéo lê.', 'Go slowly', 'Berjalan lambat'),
('夕', 'xī', 3, 'Tịch: Buổi chiều tối.', 'Evening', 'Sore'),
('大', 'dà', 3, 'Đại: To lớn.', 'Big, great', 'Besar'),
('女', 'nǚ', 3, 'Nữ: Phụ nữ, con gái.', 'Woman, female', 'Wanita, perempuan'),
('子', 'zǐ', 3, 'Tử: Con, con trai, hạt.', 'Child, seed', 'Anak, benih'),
('宀', 'mián', 3, 'Miên: Mái nhà.', 'Roof', 'Atap'),
('寸', 'cùn', 3, 'Thốn: Tấc, đơn vị đo lường.', 'Inch', 'Inci'),
('小', 'xiǎo', 3, 'Tiểu: Nhỏ bé.', 'Small', 'Kecil'),
('尢', 'wāng', 3, 'Uông: Què, thọt.', 'Lame', 'Lumpuh'),
('尸', 'shī', 3, 'Thi: Thi thể, xác chết.', 'Corpse', 'Mayat'),
('屮', 'chè', 3, 'Triệt: Mầm non, chồi non.', 'Sprout', 'Kecambah'),
('山', 'shān', 3, 'Sơn: Núi.', 'Mountain', 'Gunung'),
('巛', 'chuān', 3, 'Xuyên: Sông ngòi.', 'River', 'Sungai'),
('工', 'gōng', 3, 'Công: Người thợ, công việc.', 'Work, skill', 'Pekerjaan, keterampilan'),
('己', 'jǐ', 3, 'Kỷ: Bản thân, mình.', 'Oneself', 'Diri sendiri'),
('巾', 'jīn', 3, 'Cân: Cái khăn.', 'Turban, scarf', 'Sorban, syal'),
('干', 'gān', 3, 'Can: Thiên can, cái mộc, khô.', 'Dry, shield', 'Kering, perisai'),
('幺', 'yāo', 3, 'Yêu: Nhỏ bé, non nớt.', 'Short thread', 'Benang pendek'),
('广', 'yǎn', 3, 'Nghiễm: Mái hiên, chỗ tựa.', 'Dotted cliff', 'Tebing bertitik'),
('廴', 'yǐn', 3, 'Dẫn: Bước đi xa, kéo dài.', 'Long stride', 'Langkah panjang'),
('廾', 'gǒng', 3, 'Củng: Chắp hai tay.', 'Two hands', 'Dua tangan'),
('弋', 'yì', 3, 'Dặc: Cọc buộc, bắn tên.', 'Shoot with bow', 'Tembak dengan panah'),
('弓', 'gōng', 3, 'Cung: Cái cung bắn tên.', 'Bow', 'Busur'),
('彐', 'jì', 3, 'Ký: Đầu con heo.', 'Snout', 'Moncong'),
('彡', 'shān', 3, 'Sam: Lông tóc rủ xuống, nét vằn.', 'Bristle', 'Bulu'),
('彳', 'chì', 3, 'Xích: Bước chân trái, đi chậm.', 'Step', 'Langkah'),
('心', 'xīn', 4, 'Tâm: Trái tim, tâm trí.', 'Heart', 'Hati'),
('戈', 'gē', 4, 'Qua: Cái mác (vũ khí).', 'Halberd', 'Tombak'),
('戶', 'hù', 4, 'Hộ: Cửa một cánh, gia đình.', 'Door', 'Pintu'),
('手', 'shǒu', 4, 'Thủ: Cái tay.', 'Hand', 'Tangan'),
('支', 'zhī', 4, 'Chi: Cành, nhánh.', 'Branch', 'Cabang'),
('攴', 'pū', 4, 'Phộc: Đánh nhẹ.', 'Rap', 'Ketukan'),
('文', 'wén', 4, 'Văn: Văn hóa, văn chương.', 'Script, literature', 'Naskah, sastra'),
('斗', 'dǒu', 4, 'Đẩu: Cái đấu để đong.', 'Dipper', 'Gayung'),
('斤', 'jīn', 4, 'Cân: Cái búa, cái rìu.', 'Axe', 'Kapak'),
('方', 'fāng', 4, 'Phương: Vuông, phương hướng.', 'Square', 'Persegi'),
('无', 'wú', 4, 'Vô: Không có.', 'Not', 'Tidak'),
('日', 'rì', 4, 'Nhật: Mặt trời, ngày.', 'Sun, day', 'Matahari, hari'),
('曰', 'yuē', 4, 'Viết: Nói rằng.', 'Say', 'Berkata'),
('月', 'yuè', 4, 'Nguyệt: Mặt trăng, tháng.', 'Moon, month', 'Bulan'),
('木', 'mù', 4, 'Mộc: Cây cối, gỗ.', 'Tree', 'Pohon'),
('欠', 'qiàn', 4, 'Khiếm: Khiếm khuyết, nợ, thiếu.', 'Lack, yawn', 'Kekurangan, menguap'),
('止', 'zhǐ', 4, 'Chỉ: Dừng lại.', 'Stop', 'Berhenti'),
('歹', 'dǎi', 4, 'Ngạt: Xương tàn, chết, xấu.', 'Death, bad', 'Kematian, buruk'),
('殳', 'shū', 4, 'Thù: Cây gậy, binh khí.', 'Weapon', 'Senjata'),
('毋', 'wú', 4, 'Vô: Chớ, đừng.', 'Do not', 'Jangan'),
('比', 'bǐ', 4, 'Tỷ: So sánh.', 'Compare', 'Bandingkan'),
('毛', 'máo', 4, 'Mao: Lông, tóc.', 'Hair', 'Rambut'),
('氏', 'shì', 4, 'Thị: Họ (của con người).', 'Clan', 'Klan'),
('气', 'qì', 4, 'Khí: Khí, hơi thở.', 'Steam, breath', 'Uap, napas'),
('水', 'shuǐ', 4, 'Thủy: Nước.', 'Water', 'Air'),
('火', 'huǒ', 4, 'Hỏa: Lửa.', 'Fire', 'Api'),
('爪', 'zhǎo', 4, 'Trảo: Móng vuốt.', 'Claw', 'Cakar'),
('父', 'fù', 4, 'Phụ: Cha.', 'Father', 'Ayah'),
('爻', 'yáo', 4, 'Hào: Giao nhau, nét vạch.', 'Trigram', 'Trigram'),
('爿', 'qiáng', 4, 'Tường: Mảnh gỗ, giường.', 'Split wood', 'Kayu belah'),
('片', 'piàn', 4, 'Phiến: Mảnh mỏng, miếng.', 'Slice', 'Irisan'),
('牙', 'yá', 4, 'Nha: Răng.', 'Fang', 'Taring'),
('牛', 'niú', 4, 'Ngưu: Con bò, trâu.', 'Cow', 'Sapi'),
('犬', 'quǎn', 4, 'Khuyển: Con chó.', 'Dog', 'Anjing'),
('玄', 'xuán', 5, 'Huyền: Màu đen, bí ẩn.', 'Profound, dark', 'Sangat dalam, gelap'),
('玉', 'yù', 5, 'Ngọc: Đá quý, ngọc.', 'Jade', 'Giok'),
('瓜', 'guā', 5, 'Qua: Quả dưa.', 'Melon', 'Melon'),
('瓦', 'wǎ', 5, 'Ngõa: Ngói đất nung.', 'Tile', 'Ubin'),
('甘', 'gān', 5, 'Cam: Ngọt.', 'Sweet', 'Manis'),
('生', 'shēng', 5, 'Sinh: Sinh sản, sống.', 'Life', 'Kehidupan'),
('用', 'yòng', 5, 'Dụng: Sử dụng.', 'Use', 'Gunakan'),
('田', 'tián', 5, 'Điền: Ruộng.', 'Field', 'Ladang'),
('疋', 'pǐ', 5, 'Thất: Cuộn vải.', 'Bolt of cloth', 'Gulungan kain'),
('疒', 'chuáng', 5, 'Nạch: Tật bệnh.', 'Sickness', 'Penyakit'),
('癶', 'bō', 5, 'Bát: Bước ngược hai chân.', 'Footsteps', 'Jejak kaki'),
('白', 'bái', 5, 'Bạch: Màu trắng.', 'White', 'Putih'),
('皮', 'pí', 5, 'Bì: Da.', 'Skin', 'Kulit'),
('皿', 'mǐn', 5, 'Mãnh: Bát đĩa.', 'Dish', 'Piring'),
('目', 'mù', 5, 'Mục: Con mắt.', 'Eye', 'Mata'),
('矛', 'máo', 5, 'Mâu: Giáo mác.', 'Spear', 'Tombak'),
('矢', 'shǐ', 5, 'Thỉ: Cây mũi tên.', 'Arrow', 'Panah'),
('石', 'shí', 5, 'Thạch: Đá.', 'Stone', 'Batu'),
('示', 'shì', 5, 'Thị: Hiển thị, cúng tế.', 'Spirit', 'Roh'),
('禸', 'róu', 5, 'Nhựu: Vết chân thú.', 'Track', 'Jejak'),
('禾', 'hé', 5, 'Hòa: Cây lúa.', 'Grain', 'Biji-bijian'),
('穴', 'xué', 5, 'Huyệt: Hang lỗ.', 'Cave', 'Gua'),
('立', 'lì', 5, 'Lập: Đứng.', 'Stand', 'Berdiri'),
('竹', 'zhú', 6, 'Trúc: Cây tre trúc.', 'Bamboo', 'Bambu'),
('米', 'mǐ', 6, 'Mễ: Gạo.', 'Rice', 'Beras'),
('糸', 'mì', 6, 'Mịch: Sợi tơ nhỏ.', 'Silk', 'Sutra'),
('缶', 'fǒu', 6, 'Phẫu: Chậu sành.', 'Jar', 'Guci'),
('网', 'wǎng', 6, 'Võng: Cái lưới.', 'Net', 'Jaring'),
('羊', 'yáng', 6, 'Dương: Con dê.', 'Sheep', 'Domba'),
('羽', 'yǔ', 6, 'Vũ: Lông vũ, cánh.', 'Feather', 'Bulu burung'),
('老', 'lǎo', 6, 'Lão: Già cả.', 'Old', 'Tua'),
('而', 'ér', 6, 'Nhi: Mà, và.', 'And', 'Dan'),
('耒', 'lěi', 6, 'Lỗi: Cái cày.', 'Plow', 'Bajak'),
('耳', 'ěr', 6, 'Nhĩ: Cái tai.', 'Ear', 'Telinga'),
('聿', 'yù', 6, 'Duật: Cây bút.', 'Brush', 'Kuas'),
('肉', 'ròu', 6, 'Nhục: Thịt.', 'Meat', 'Daging'),
('臣', 'chén', 6, 'Thần: Quan thần.', 'Minister', 'Menteri'),
('自', 'zì', 6, 'Tự: Tự bản thân, từ.', 'Self', 'Diri'),
('至', 'zhì', 6, 'Chí: Đến nơi.', 'Arrive', 'Tiba'),
('臼', 'jiù', 6, 'Cữu: Cái cối giã gạo.', 'Mortar', 'Lesung'),
('舌', 'shé', 6, 'Thiệt: Cái lưỡi.', 'Tongue', 'Lidah'),
('舛', 'chuǎn', 6, 'Suyễn: Sai trái, lầm lỗi.', 'Oppose', 'Menentang'),
('舟', 'zhōu', 6, 'Chu: Chiếc thuyền.', 'Boat', 'Perahu'),
('艮', 'gèn', 6, 'Cấn: Quẻ cấn, ngăn lại.', 'Stopping', 'Berhenti'),
('色', 'sè', 6, 'Sắc: Màu sắc, nhan sắc.', 'Color', 'Warna'),
('艸', 'cǎo', 6, 'Thảo: Cỏ cây.', 'Grass', 'Rumput'),
('虍', 'hū', 6, 'Hô: Vằn vện con hổ.', 'Tiger', 'Harimau'),
('虫', 'chóng', 6, 'Trùng: Côn trùng.', 'Insect', 'Serangga'),
('血', 'xuè', 6, 'Huyết: Máu.', 'Blood', 'Darah'),
('行', 'xíng', 6, 'Hành: Đi, thi hành.', 'Walk, enclosure', 'Berjalan, kandang'),
('衣', 'yī', 6, 'Y: Áo.', 'Clothes', 'Pakaian'),
('襾', 'yà', 6, 'Á: Che đậy.', 'Cover', 'Penutup'),
('見', 'jiàn', 7, 'Kiến: Trông thấy.', 'See', 'Melihat'),
('角', 'jiǎo', 7, 'Giác: Góc, sừng thú.', 'Horn', 'Tanduk'),
('言', 'yán', 7, 'Ngôn: Nói, lời nói.', 'Speech', 'Bicara'),
('谷', 'gǔ', 7, 'Cốc: Khe núi.', 'Valley', 'Lembah'),
('豆', 'dòu', 7, 'Đậu: Hạt đậu.', 'Bean', 'Kacang'),
('豕', 'shǐ', 7, 'Thỉ: Con heo.', 'Pig', 'Babi'),
('豸', 'zhì', 7, 'Trãi: Loài thú không chân.', 'Badger', 'Luwak'),
('貝', 'bèi', 7, 'Bối: Vỏ sò, tiền bạc.', 'Shell', 'Cangkang'),
('赤', 'chì', 7, 'Xích: Màu đỏ.', 'Red', 'Merah'),
('走', 'zǒu', 7, 'Tẩu: Đi bộ, chạy.', 'Run', 'Lari'),
('足', 'zú', 7, 'Túc: Cái chân, đầy đủ.', 'Foot', 'Kaki'),
('身', 'shēn', 7, 'Thân: Thân thể.', 'Body', 'Tubuh'),
('車', 'chē', 7, 'Xa: Chiếc xe.', 'Cart', 'Gerobak'),
('辛', 'xīn', 7, 'Tân: Cay, khó nhọc.', 'Bitter', 'Pahit'),
('辰', 'chén', 7, 'Thần: Ngôi sao, thìn.', 'Morning', 'Pagi'),
('辵', 'chuò', 7, 'Xước: Bước đi lúc dừng lúc chạy.', 'Walk', 'Berjalan'),
('邑', 'yì', 7, 'Ấp: Làng xóm.', 'City', 'Kota'),
('酉', 'yǒu', 7, 'Dậu: Canh giờ, rượu.', 'Wine', 'Anggur'),
('釆', 'biàn', 7, 'Biện: Phân biệt.', 'Distinguish', 'Membedakan'),
('里', 'lǐ', 7, 'Lý: Dặm, làng, bên trong.', 'Village, mile', 'Desa, mil'),
('金', 'jīn', 8, 'Kim: Kim loại, vàng.', 'Gold', 'Emas'),
('長', 'cháng', 8, 'Trường: Dài, người lớn tuổi.', 'Long', 'Panjang'),
('門', 'mén', 8, 'Môn: Cánh cửa.', 'Gate', 'Gerbang'),
('阜', 'fù', 8, 'Phụ: Đồi đất.', 'Mound', 'Gundukan'),
('隶', 'lì', 8, 'Đãi: Kịp, bắt lấy.', 'Slave', 'Budak'),
('隹', 'zhuī', 8, 'Truy: Loài chim đuôi ngắn.', 'Short-tailed bird', 'Burung ekor pendek'),
('雨', 'yǔ', 8, 'Vũ: Mưa.', 'Rain', 'Hujan'),
('青', 'qīng', 8, 'Thanh: Màu xanh.', 'Blue', 'Biru'),
('非', 'fēi', 8, 'Phi: Sai trái.', 'Wrong', 'Salah'),
('面', 'miàn', 9, 'Diện: Khuôn mặt.', 'Face', 'Wajah'),
('革', 'gé', 9, 'Cách: Da sống.', 'Leather', 'Kulit'),
('韋', 'wéi', 9, 'Vi: Da đã thuộc.', 'Tanned leather', 'Kulit samak'),
('韭', 'jiǔ', 9, 'Cửu: Hẹ.', 'Leek', 'Daun bawang'),
('音', 'yīn', 9, 'Âm: Âm thanh.', 'Sound', 'Suara'),
('頁', 'yè', 9, 'Hiệt: Đầu, trang sách.', 'Leaf', 'Daun'),
('風', 'fēng', 9, 'Phong: Gió.', 'Wind', 'Angin'),
('飛', 'fēi', 9, 'Phi: Bay.', 'Fly', 'Terbang'),
('食', 'shí', 9, 'Thực: Ăn uống.', 'Eat', 'Makan'),
('首', 'shǒu', 9, 'Thủ: Cái đầu.', 'Head', 'Kepala'),
('香', 'xiāng', 9, 'Hương: Mùi thơm.', 'Fragrant', 'Harum'),
('馬', 'mǎ', 10, 'Mã: Con ngựa.', 'Horse', 'Kuda'),
('骨', 'gǔ', 10, 'Cốt: Xương.', 'Bone', 'Tulang'),
('高', 'gāo', 10, 'Cao: Cao.', 'Tall', 'Tinggi'),
('髟', 'biāo', 10, 'Bưu: Tóc rủ xuống.', 'Hair', 'Rambut'),
('鬥', 'dòu', 10, 'Đấu: Chiến đấu.', 'Fight', 'Bertarung'),
('鬯', 'chàng', 10, 'Sưởng: Rượu dùng cúng tế.', 'Sacrificial wine', 'Anggur pengorbanan'),
('鬲', 'lì', 10, 'Cách: Cái vạc.', 'Cauldron', 'Kuali'),
('鬼', 'guǐ', 10, 'Quỷ: Ma quỷ.', 'Ghost', 'Hantu'),
('魚', 'yú', 11, 'Ngư: Con cá.', 'Fish', 'Ikan'),
('鳥', 'niǎo', 11, 'Điểu: Con chim.', 'Bird', 'Burung'),
('鹵', 'lǔ', 11, 'Lỗ: Đất mặn.', 'Salt', 'Garam'),
('鹿', 'lù', 11, 'Lộc: Con hươu.', 'Deer', 'Rusa'),
('麥', 'mài', 11, 'Mạch: Lúa mạch.', 'Wheat', 'Gandum'),
('麻', 'má', 11, 'Ma: Cây gai.', 'Hemp', 'Rami'),
('黃', 'huáng', 12, 'Hoàng: Màu vàng.', 'Yellow', 'Kuning'),
('黍', 'shǔ', 12, 'Thử: Lúa nếp.', 'Millet', 'Jawawut'),
('黑', 'hēi', 12, 'Hắc: Màu đen.', 'Black', 'Hitam'),
('黹', 'zhǐ', 12, 'Chỉ: Khâu vá.', 'Embroidery', 'Bordir'),
('黽', 'mǐn', 13, 'Mãnh: Con ếch.', 'Frog', 'Katak'),
('鼎', 'dǐng', 13, 'Đỉnh: Cái vạc ba chân.', 'Tripod', 'Tripod'),
('鼓', 'gǔ', 13, 'Cổ: Cái trống.', 'Drum', 'Drum'),
('鼠', 'shǔ', 13, 'Thử: Con chuột.', 'Rat', 'Tikus'),
('鼻', 'bí', 14, 'Tỵ: Cái mũi.', 'Nose', 'Hidung'),
('齊', 'qí', 14, 'Tề: Đều đặn.', 'Even', 'Rata'),
('齒', 'chǐ', 15, 'Xỉ: Răng.', 'Tooth', 'Gigi'),
('龍', 'lóng', 16, 'Long: Con rồng.', 'Dragon', 'Naga'),
('龜', 'guī', 16, 'Quy: Con rùa.', 'Turtle', 'Kura-kura'),
('龠', 'yuè', 17, 'Dược: Sáo thổi.', 'Flute', 'Suling');
