'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'vi' | 'en' | 'id';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    'menu.home': 'Trang chủ',
    'menu.platform': 'Nền tảng',
    'menu.pinyin': 'Bảng Pinyin',
    'menu.radicals': '214 Bộ Thủ',
    'menu.rules': 'Quy tắc chuyển âm',
    'menu.personalize': 'Cá nhân hoá',
    'menu.route': 'Lộ trình',
    'menu.review': 'Ôn tập',
    'menu.vocab': 'Sổ tay từ vựng',
    'menu.grammar': 'Sổ tay ngữ pháp',
    'menu.progress': 'Tiến độ học',
    'menu.dictionary': 'Tra từ điển',
    'menu.dict-search': 'Tra từ điển',
    'menu.character-analysis': 'Phân tích Hán tự',
    'menu.shadowing': 'Shadowing',
    'menu.lessons': 'Bài khoá',
    'menu.certificates': 'Luyện thi chứng chỉ',
    'menu.create-file': 'Tạo file',
    'menu.leaderboard': 'Bảng xếp hạng',
    'menu.feedback': 'Phản hồi',
    'menu.settings': 'Cài đặt',
    'hero.hello': 'Chào',
    'hero.defaultName': 'bạn',
    'hero.intro': 'Tiếp tục hành trình từ vựng tiếng Đài Loan của bạn — mỗi ngày một chút là đủ.',
    'hero.joinCommunity': 'Vào nhóm học cùng mọi người nhé:',
    'hero.communityName': 'Nhai tiếng Đài Loan mỗi ngày',
    'header.streakTitle': 'Chuỗi ngày học liên tục',
    'header.notifTitle': 'Thông báo',
    'header.noNotif': 'Chưa có thông báo',
    'header.accountSettings': 'Cài đặt tài khoản',
    'header.terms': 'Điều khoản & chính sách',
    'header.logout': 'Đăng xuất',
    'header.login': 'Đăng nhập',
    'header.login': 'Đăng nhập',
    'header.defaultUser': 'Người dùng',
    'course.home': 'Trang chủ',
    'course.lessonCount': 'bài',
    'course.skills': 'KỸ NĂNG',
    'course.vocabTab': '✨ Từ vựng - 词汇',
    'course.grammarTab': '📄 Ngữ pháp - 语法',
    'course.hanziTab': '🖍 Chữ Hán - 汉字',
    'course.progressTitle': 'Tiến độ học',
    'course.lessonsLabel': 'BÀI HỌC',
    'course.emptyLesson': 'Chưa có bài học nào',
    'course.vocabUnit': 'từ vựng',
    'course.patternUnit': 'mẫu',
    'course.newHanzi': 'chữ Hán mới trong cuốn này',
    'course.flashcard': 'Flashcard',
    'course.practice': 'Luyện viết',
    'course.createFile': 'Tạo file',
    'course.grammarUnit': 'mẫu ngữ pháp',
    'home.improvedVersion': 'Bản cải tiến',
    'practice.title': 'Tạo file luyện viết',
    'practice.print': 'In tài liệu',
    'practice.close': 'Đóng',
    'chat.message': 'Nhắn tin',
    'chat.botTitle': '🤖 Trợ lý Nhai TOCFL',
    'chat.botGreeting': 'Chào bạn! Mình là trợ lý Nhai TOCFL. Bạn đang muốn bắt đầu học cấp độ nào?',
    'chat.quick1': 'Lộ trình TOCFL 1',
    'chat.quick2': 'TOCFL 3.0 khác gì 2.0?',
    'chat.quick3': 'Mẹo nhớ chữ Hán',
    'chat.closeAria': 'Đóng khung chat',
    'chat.inputPlaceholder': 'Nhập câu hỏi...',
    'chat.sendAria': 'Gửi tin nhắn',
    'chat.triggerAria': 'Nhắn tin hỗ trợ',
    'chat.replyDefault': 'Cảm ơn câu hỏi của bạn! Hãy nhấp vào một trong các thẻ TOCFL trên màn hình để bắt đầu học ngay nhé!',
    'chat.replyRoute': 'TOCFL 1 bản mới gồm 333 từ vựng và 41 mẫu câu căn bản, bạn nên học phát âm pinyin chuẩn trước tiên nhé!',
    'chat.replyTOCFL3': 'TOCFL 3.0 chia thành 3 giai đoạn và 9 cấp độ (thay vì 6 cấp như trước), bổ sung thêm nhiều từ vựng và kỹ năng giao tiếp thực tế hơn!',
    'settings.title': 'Cài đặt',
    'settings.subtitle': 'Chế độ hiển thị, ngôn ngữ giao diện, giọng đọc và trợ lý AI.',
    'settings.theme': 'Chế độ hiển thị',
    'settings.theme.light': 'Sáng',
    'settings.theme.dark': 'Tối',
    'settings.language': 'Ngôn ngữ giao diện',
    'home.title': 'Trang chủ',
    'lesson.vocab': 'Từ vựng',
    'lesson.grammar': 'Ngữ pháp',
    'lesson.hanzi': 'Chữ Hán',
    'lesson.auto': 'Tự động',
    'lesson.stop': 'Dừng phát',
    'lesson.list': 'Danh sách bài',
    'lesson.print': 'In file',
    'lesson.addReview': 'Thêm cả bài vào ôn tập',
    'lesson.hint': '✨ Click để lật xem nghĩa',
    'lesson.unstudied': 'Chưa học',
    'lesson.quiz': 'Trắc nghiệm',
    'lesson.typing': 'Gõ từ',
    'lesson.reading': 'Đọc hiểu',
    'lesson.listening': 'Nghe ghép câu',
    'lesson.loading': 'Đang tải...',
    'lesson.vocabUnit': 'từ vựng',
    'lesson.hskVocab': 'Từ vựng HSK',
    'lesson.prev': 'Trước',
    'lesson.next': 'Sau',
    'lesson.notMemorized': 'Chưa thuộc',
    'lesson.memorized': 'Đã thuộc',
    'lesson.chooseMode': 'Chọn chế độ học',
    'auto.title': 'Tự động phát thẻ',
    'auto.flipTime': 'Thời gian để lật thẻ',
    'auto.flipDesc': 'Hiện mặt trước bao lâu rồi lật sang mặt sau',
    'auto.seconds': 'giây',
    'auto.nextTime': 'Thời gian để sang thẻ mới',
    'auto.nextDesc': 'Xem mặt sau bao lâu rồi chuyển thẻ kế tiếp',
    'auto.listenVocab': 'Nghe từ vựng',
    'auto.listenVocabDesc': 'Đọc xong từ mới bắt đầu đếm thời gian',
    'auto.listenExample': 'Nghe câu ví dụ',
    'auto.listenExampleDesc': 'Đọc xong câu ví dụ mới bắt đầu đếm thời gian',
    'auto.repeat': 'Số lần nghe lại',
    'auto.repeatDesc': 'Đọc tuần tự đủ số lần rồi mới lật/sang thẻ',
    'auto.times': 'lần',
    'auto.cancel': 'Hủy',
    'auto.start': 'Bắt đầu',
    'login.title': 'Đăng nhập',
    'login.subtitle': 'Đăng nhập để đồng bộ tiến trình học của bạn.',
    'login.close': 'Đóng',
    'login.google': 'Đăng nhập bằng Google',
    'login.or': 'HOẶC',
    'login.password': 'Mật khẩu',
    'login.submit': 'Đăng nhập',
    'login.terms': 'Bằng việc đăng nhập, bạn đồng ý với Điều khoản sử dụng và Chính sách quyền riêng tư.'
  },
  en: {
    'menu.home': 'Home',
    'menu.platform': 'Platform',
    'menu.pinyin': 'Pinyin Chart',
    'menu.radicals': '214 Radicals',
    'menu.rules': 'Phonetic Rules',
    'menu.personalize': 'Personalize',
    'menu.route': 'Learning Route',
    'menu.review': 'Review',
    'menu.vocab': 'Vocab Notebook',
    'menu.grammar': 'Grammar Notebook',
    'menu.progress': 'Progress',
    'menu.dictionary': 'Dictionary',
    'menu.dict-search': 'Search Dictionary',
    'menu.character-analysis': 'Character Analysis',
    'menu.shadowing': 'Shadowing',
    'menu.lessons': 'Lessons',
    'menu.certificates': 'Certificates',
    'menu.create-file': 'Create File',
    'menu.leaderboard': 'Leaderboard',
    'menu.feedback': 'Feedback',
    'menu.settings': 'Settings',
    'hero.hello': 'Hello',
    'hero.defaultName': 'there',
    'hero.intro': 'Continue your Taiwanese vocabulary journey — a little bit every day is enough.',
    'hero.joinCommunity': 'Join the study group with everyone:',
    'hero.communityName': 'Chew Taiwanese everyday',
    'header.streakTitle': 'Study streak',
    'header.notifTitle': 'Notifications',
    'header.noNotif': 'No notifications',
    'header.accountSettings': 'Account Settings',
    'header.terms': 'Terms & Policies',
    'header.logout': 'Logout',
    'header.login': 'Login',
    'header.login': 'Login',
    'header.defaultUser': 'User',
    'course.home': 'Home',
    'course.lessonCount': 'lessons',
    'course.skills': 'SKILLS',
    'course.vocabTab': '✨ Vocabulary - 词汇',
    'course.grammarTab': '📄 Grammar - 语法',
    'course.hanziTab': '🖍 Characters - 汉字',
    'course.progressTitle': 'Progress',
    'course.lessonsLabel': 'LESSONS',
    'course.emptyLesson': 'No lessons yet',
    'course.vocabUnit': 'words',
    'course.patternUnit': 'patterns',
    'course.newHanzi': 'new characters in this book',
    'course.flashcard': 'Flashcard',
    'course.practice': 'Practice',
    'course.createFile': 'Export',
    'course.grammarUnit': 'grammar patterns',
    'home.improvedVersion': 'Improved Version',
    'practice.title': 'Create practice sheet',
    'practice.print': 'Print document',
    'practice.close': 'Close',
    'chat.message': 'Message',
    'chat.botTitle': '🤖 Nhai TOCFL Assistant',
    'chat.botGreeting': 'Hello! I am the Nhai TOCFL assistant. Which level would you like to start with?',
    'chat.quick1': 'TOCFL 1 Route',
    'chat.quick2': 'TOCFL 3.0 vs 2.0?',
    'chat.quick3': 'Hanzi Tips',
    'chat.closeAria': 'Close chat',
    'chat.inputPlaceholder': 'Type a question...',
    'chat.sendAria': 'Send message',
    'chat.triggerAria': 'Support chat',
    'chat.replyDefault': 'Thank you for your question! Please click on one of the TOCFL cards on the screen to start learning right away!',
    'chat.replyRoute': 'The new TOCFL 1 includes 333 words and 41 basic sentence patterns, you should learn standard pinyin pronunciation first!',
    'chat.replyTOCFL3': 'TOCFL 3.0 is divided into 3 bands and 9 levels (instead of 6 levels like before), adding more practical vocabulary and communication skills!',
    'settings.title': 'Settings',
    'settings.subtitle': 'Display mode, interface language, reading voice and AI assistant.',
    'settings.theme': 'Display Mode',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.language': 'Interface Language',
    'home.title': 'Home',
    'lesson.vocab': 'Vocabulary',
    'lesson.grammar': 'Grammar',
    'lesson.hanzi': 'Characters',
    'lesson.auto': 'Auto-play',
    'lesson.stop': 'Stop',
    'lesson.list': 'Lesson List',
    'lesson.print': 'Print file',
    'lesson.addReview': 'Add lesson to review',
    'lesson.hint': '✨ Click to flip for meaning',
    'lesson.unstudied': 'Unstudied',
    'lesson.quiz': 'Quiz',
    'lesson.typing': 'Typing',
    'lesson.reading': 'Reading',
    'lesson.listening': 'Listening',
    'lesson.loading': 'Loading...',
    'lesson.vocabUnit': 'words',
    'lesson.hskVocab': 'HSK Vocabulary',
    'lesson.prev': 'Prev',
    'lesson.next': 'Next',
    'lesson.notMemorized': 'Not Memorized',
    'lesson.memorized': 'Memorized',
    'lesson.chooseMode': 'Choose study mode',
    'auto.title': 'Auto-play Cards',
    'auto.flipTime': 'Time to flip card',
    'auto.flipDesc': 'How long to show front before flipping',
    'auto.seconds': 'secs',
    'auto.nextTime': 'Time to next card',
    'auto.nextDesc': 'How long to show back before next card',
    'auto.listenVocab': 'Listen to word',
    'auto.listenVocabDesc': 'Timer starts after reading word',
    'auto.listenExample': 'Listen to example',
    'auto.listenExampleDesc': 'Timer starts after reading example',
    'auto.repeat': 'Repeat count',
    'auto.repeatDesc': 'Read multiple times before flipping/next',
    'auto.times': 'times',
    'auto.cancel': 'Cancel',
    'auto.start': 'Start',
    'login.title': 'Login',
    'login.subtitle': 'Login to sync your learning progress.',
    'login.close': 'Close',
    'login.google': 'Continue with Google',
    'login.or': 'OR',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.terms': 'By logging in, you agree to the Terms of Service and Privacy Policy.'
  },
  id: {
    'menu.home': 'Beranda',
    'menu.platform': 'Platform',
    'menu.pinyin': 'Bagan Pinyin',
    'menu.radicals': '214 Radikal',
    'menu.rules': 'Aturan Fonetik',
    'menu.personalize': 'Personalisasi',
    'menu.route': 'Rute Belajar',
    'menu.review': 'Ulasan',
    'menu.vocab': 'Buku Kosakata',
    'menu.grammar': 'Buku Tata Bahasa',
    'menu.progress': 'Kemajuan',
    'menu.dictionary': 'Kamus',
    'menu.dict-search': 'Cari Kamus',
    'menu.character-analysis': 'Analisis Karakter',
    'menu.shadowing': 'Shadowing',
    'menu.lessons': 'Pelajaran',
    'menu.certificates': 'Sertifikat',
    'menu.create-file': 'Buat File',
    'menu.leaderboard': 'Papan Peringkat',
    'menu.feedback': 'Umpan Balik',
    'menu.settings': 'Pengaturan',
    'hero.hello': 'Halo',
    'hero.defaultName': 'teman',
    'hero.intro': 'Lanjutkan perjalanan kosakata Taiwan Anda — sedikit setiap hari sudah cukup.',
    'hero.joinCommunity': 'Bergabunglah dengan grup belajar bersama semuanya:',
    'hero.communityName': 'Nhai bahasa Taiwan setiap hari',
    'header.streakTitle': 'Rentetan belajar',
    'header.notifTitle': 'Pemberitahuan',
    'header.noNotif': 'Tidak ada pemberitahuan',
    'header.accountSettings': 'Pengaturan Akun',
    'header.terms': 'Syarat & Kebijakan',
    'header.logout': 'Keluar',
    'header.login': 'Masuk',
    'header.login': 'Masuk',
    'header.defaultUser': 'Pengguna',
    'course.home': 'Beranda',
    'course.lessonCount': 'pelajaran',
    'course.skills': 'KETERAMPILAN',
    'course.vocabTab': '✨ Kosakata - 词汇',
    'course.grammarTab': '📄 Tata Bahasa - 语法',
    'course.hanziTab': '🖍 Karakter - 汉字',
    'course.progressTitle': 'Kemajuan',
    'course.lessonsLabel': 'PELAJARAN',
    'course.emptyLesson': 'Belum ada pelajaran',
    'course.vocabUnit': 'kata',
    'course.patternUnit': 'pola',
    'course.newHanzi': 'karakter baru dalam buku ini',
    'course.flashcard': 'Kartu Flash',
    'course.practice': 'Latihan',
    'course.createFile': 'Buat File',
    'course.grammarUnit': 'pola tata bahasa',
    'home.improvedVersion': 'Versi yang ditingkatkan',
    'practice.title': 'Buat lembar latihan',
    'practice.print': 'Cetak dokumen',
    'practice.close': 'Tutup',
    'chat.message': 'Pesan',
    'chat.botTitle': '🤖 Asisten Nhai TOCFL',
    'chat.botGreeting': 'Halo! Saya asisten Nhai TOCFL. Anda ingin mulai belajar di tingkat mana?',
    'chat.quick1': 'Rute TOCFL 1',
    'chat.quick2': 'TOCFL 3.0 vs 2.0?',
    'chat.quick3': 'Tips Hanzi',
    'chat.closeAria': 'Tutup obrolan',
    'chat.inputPlaceholder': 'Ketik pertanyaan...',
    'chat.sendAria': 'Kirim pesan',
    'chat.triggerAria': 'Obrolan dukungan',
    'chat.replyDefault': 'Terima kasih atas pertanyaannya! Silakan klik salah satu kartu TOCFL di layar untuk mulai belajar segera!',
    'chat.replyRoute': 'TOCFL 1 baru mencakup 333 kata dan 41 pola kalimat dasar, Anda harus belajar pengucapan pinyin standar terlebih dahulu!',
    'chat.replyTOCFL3': 'TOCFL 3.0 dibagi menjadi 3 band dan 9 tingkat (bukan 6 tingkat seperti sebelumnya), menambah kosakata yang lebih praktis dan keterampilan komunikasi!',
    'settings.title': 'Pengaturan',
    'settings.subtitle': 'Mode tampilan, bahasa antarmuka, suara bacaan, dan asisten AI.',
    'settings.theme': 'Mode Tampilan',
    'settings.theme.light': 'Terang',
    'settings.theme.dark': 'Gelap',
    'settings.language': 'Bahasa Antarmuka',
    'home.title': 'Beranda',
    'lesson.vocab': 'Kosakata',
    'lesson.grammar': 'Tata Bahasa',
    'lesson.hanzi': 'Karakter',
    'lesson.auto': 'Putar Otomatis',
    'lesson.stop': 'Berhenti',
    'lesson.list': 'Daftar Pelajaran',
    'lesson.print': 'Cetak file',
    'lesson.addReview': 'Tambahkan ke ulasan',
    'lesson.hint': '✨ Klik untuk membalik arti'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<Language>('vi');

  useEffect(() => {
    const savedLang = localStorage.getItem('app-lang') as Language;
    if (savedLang && (savedLang === 'vi' || savedLang === 'en' || savedLang === 'id')) {
      setLangState(savedLang);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('app-lang', newLang);
  };

  const t = (key: string): string => {
    return (translations[lang] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
